### ISSUE TITLE
How to exit from webR after running code such as in the example index.js

### ISSUE THREAD

**Issue by jbodart-argenx** [georgestagg/webr-node-example#1]
Hello,

I can successfully run the example code with `node index.js`.  This displays 10 normally distributed random numbers, but then the program keeps waiting and I need to use `CTRL-C` to terminate it.  What should be added to index.js for the program to return to the caller ?

I wish to create a module that exports a function to make some computation in webR then return the result to the (Javascript) caller, could you provide an example for that ?

Thanks a lot!

**Comment by georgestagg** [comment]
Hi @jbodart-argenx,

The short version is to execute `webR.close()` once you are finished using webR, and then the node process will exit cleanly.

```js
const { WebR } = require('webr');

const webR = new WebR();

(async () => {
    await webR.init();

    let result = await webR.evalR('rnorm(10,5,1)');
    try {
        let output = await result.toArray();
        console.log('Result of running `rnorm` from webR: ', output);
    } finally {
        webR.destroy(result);
    }

    webR.close();
})();
```

You should only do this once you have finished using R, or you'll need to start a new process again using `new WebR()`.

This is a consequence of the way messages are passed to the webR Worker where the WebAssembly R process is running and waiting for input. The channel between the main thread and the Worker thread is held open while R is waiting for input, until you call the `.close()` method to shut down R.

The process is inherently asynchronous and so we need to use either `Promises` with `.then()`, or make use of `async/await` before calling `.close()`.

It is possible to do some computation in webR and return it to a JS caller, but you must be sure to handle the returned `Promise` in some way (you can use either `.then()`, or "top-level await").

Here is a more inolved example, using modules for the export and import:

```js
// myModule.mjs - this is the module that will do some work in R
import { WebR } from 'webr';

const webR = new WebR();
webR.init();

// do some work
export async function myFunction(n, foo, bar) {
    await webR.init();
    const obj = await webR.evalR('rnorm(n, foo, bar)', {
        env: { n, foo, bar }
    });
    return obj.toArray();
}

// Signal you are finished using R
export function done() {
    webR.close();
}
```

```js
// index.mjs - This is your JS caller code

// Import our new custom module, this will start up R
import { done, myFunction } from './myModule.mjs'

// Execute R code using Promises
myFunction(10, 0, 1).then((ret) => {
    console.log(ret);
}).finally(() => {
    done()
});

// Alternatively, using top level await
// const ret = await myFunction(10, -2, 5);
// console.log(ret);
// done();
```
